"""Replace all hardcoded strings in student screens, widgets, and nav."""
from pathlib import Path

L = "AppLocalizations.of(context)!"
L2 = "AppLocalizations.of(context)!"
IMP = "import '../../l10n/generated/app_localizations.dart';"
IMP1 = "import '../l10n/generated/app_localizations.dart';"

FIXES = {
    # ─── applied_opportunities_screen ──────────────────────────────────────────
    "lib/screens/student/applied_opportunities_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Opportunity unavailable'",   f"title: {L}.uiOpportunityUnavailable"),
            ("title: 'Applied'",                   f"title: {L}.uiApplied"),
            ("tooltip: 'Refresh applications'",    f"tooltip: {L}.uiRefreshApplications"),
            ("title: 'Loading your applications...'", f"title: {L}.uiLoadingApplications"),
            ("label: 'Total'",                     f"label: {L}.uiTotal"),
            ("label: 'Pending'",                   f"label: {L}.uiPending"),
            ("label: 'Approved'",                  f"label: {L}.uiApproved"),
            ("label: 'Rejected'",                  f"label: {L}.uiRejected"),
        ],
    },
    # ─── saved_screen ──────────────────────────────────────────────────────────
    "lib/screens/student/saved_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Opportunity unavailable'",   f"title: {L}.uiOpportunityUnavailable"),
            ("title: 'Scholarship unavailable'",   f"title: {L}.uiScholarshipUnavailable"),
            ("title: 'Link unavailable'",          f"title: {L}.uiLinkUnavailable"),
            ("title: 'Saved'",                     f"title: {L}.uiSaved"),
            ("tooltip: 'Refresh saved items'",     f"tooltip: {L}.uiRefreshSavedItems"),
            ("title: 'Loading your saved items...'", f"title: {L}.uiLoadingSavedItems"),
            ("label: 'Total'",                     f"label: {L}.uiTotal"),
            ("label: 'Opps'",                      f"label: {L}.uiOpps"),
            ("label: 'Scholarships'",              f"label: {L}.uiScholarships"),
            ("label: 'Trainings'",                 f"label: {L}.uiTraining"),
            ("label: 'Ideas'",                     f"label: {L}.uiIdeas"),
            ("label: 'Closing soon'",              f"label: {L}.uiClosingSoon"),
            ("label: 'Free'",                      f"label: {L}.uiFree"),
            ("label: 'Certificate'",               f"label: {L}.uiCertified"),
        ],
    },
    # ─── student_dashboard_screen ──────────────────────────────────────────────
    "lib/screens/student/student_dashboard_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Jobs'",                      f"title: {L}.uiJobs"),
            ("title: 'Internships'",               f"title: {L}.uiInternships"),
            ("title: 'Sponsored'",                 f"title: {L}.uiSponsored"),
            ("title: 'Scholarships'",              f"title: {L}.uiScholarships"),
            ("title: 'Ideas'",                     f"title: {L}.uiIdeas"),
            ("title: 'CV Builder'",                f"title: {L}.uiCvBuilder"),
            ("title: 'Training'",                  f"title: {L}.uiTraining"),
            ("title: 'Saved'",                     f"title: {L}.uiSaved"),
            ("message: 'No urgent deadlines right now'", f"message: {L}.uiNoUrgentDeadlines"),
            ("message: 'No recommendations right now'",  f"message: {L}.uiNoRecommendations"),
            ("subtitle: 'Check back soon for fresh curated opportunities.'", f"subtitle: {L}.uiCheckBackSoon"),
            ("message: 'No recent activity yet'",  f"message: {L}.uiNoRecentActivity"),
            ("title: 'Link unavailable'",          f"title: {L}.uiLinkUnavailable"),
            ("title: 'Open unavailable'",          f"title: {L}.uiOpenUnavailable"),
            ("title: 'Build your CV first.'",      f"title: {L}.uiBuildCvFirst"),
            ("title: 'Complete your profile.'",    f"title: {L}.uiCompleteProfile"),
            ("title: 'Act before deadlines close.'", f"title: {L}.uiActBeforeDeadlines"),
            ("title: 'Your shortlist is ready.'",  f"title: {L}.uiShortlistReady"),
            ("subtitle: 'Revisit saved picks before the strongest deadlines slip by.'", f"subtitle: {L}.uiRevisitSavedPicks"),
            ("title: 'Find your next best opportunity.'", f"title: {L}.uiFindNextOpportunity"),
        ],
    },
    # ─── opportunities_screen ──────────────────────────────────────────────────
    "lib/screens/student/opportunities_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Login required'",            f"title: {L}.uiLoginRequired"),
            ("title: 'Discover'",                  f"title: {L}.uiDiscover"),
            ("title: 'Jobs'",                      f"title: {L}.uiJobs"),
            ("title: 'Internships'",               f"title: {L}.uiInternships"),
            ("subtitle: 'Hands-on student placements'", f"subtitle: {L}.uiInternshipsSubtitle"),
            ("title: 'Sponsored'",                 f"title: {L}.uiSponsored"),
            ("subtitle: 'Partner-backed support'", f"subtitle: {L}.uiSponsoredSubtitle"),
            ("title: 'Training Programs'",         f"title: {L}.uiTraining"),
            ("title: 'Trending Opportunities'",    f"title: {L}.uiTrendingOpportunities"),
            ("title: 'No trending opportunities right now'", f"title: {L}.uiNoTrendingOpportunities"),
            ("title: 'Latest Opportunities'",      f"title: {L}.uiLatestOpportunities"),
            ("title: 'No opportunities match this view'", f"title: {L}.uiNoOpportunitiesMatchView"),
            ("title: 'Closing Soon'",              f"title: {L}.uiClosingSoon"),
            ("title: 'No urgent deadlines right now'", f"title: {L}.uiNoUrgentDeadlines"),
            ("label: 'All'",                       f"label: {L}.uiAll"),
            ("label: 'Jobs'",                      f"label: {L}.uiJobs"),
            ("label: 'Internships'",               f"label: {L}.uiInternships"),
            ("label: 'Sponsored'",                 f"label: {L}.uiSponsored"),
            ("label: 'Any'",                       f"label: {L}.uiAny"),
            ("label: 'Paid only'",                 f"label: {L}.uiPaidOnly"),
            ("label: 'Closing soon'",              f"label: {L}.uiClosingSoon"),
            ("tooltip: 'Clear search'",            f"tooltip: {L}.uiClearSearch"),
            ("tooltip: 'Focus search'",            f"tooltip: {L}.uiFocusSearch"),
            ("tooltip: 'Filter opportunities'",    f"tooltip: {L}.uiFilterOpportunities"),
        ],
    },
    # ─── opportunity_detail_screen ─────────────────────────────────────────────
    "lib/screens/student/opportunity_detail_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Login required'",            f"title: {L}.uiLoginRequired"),
            ("title: 'Application blocked'",       f"title: {L}.uiApplicationBlocked"),
            ("title: 'CV required'",               f"title: {L}.uiCvRequired"),
            ("title: 'Application approved'",      f"title: {L}.uiApplicationApprovedB0Cb"),
            ("title: 'Chat unavailable'",          f"title: {L}.uiChatUnavailable"),
            ("label: 'Share'",                     f"label: {L}.uiShare"),
            ("tooltip: 'Share opportunity'",       f"tooltip: {L}.uiShareOpportunity"),
            ("label: 'Location'",                  f"label: {L}.uiLocation"),
            ("label: 'Deadline'",                  f"label: {L}.uiDeadline"),
            ("label: 'Posted'",                    f"label: {L}.uiPosted"),
            ("label: 'Type'",                      f"label: {L}.uiType"),
            ("label: 'Duration'",                  f"label: {L}.uiDuration"),
            ("label: 'Work mode'",                 f"label: {L}.uiWorkMode"),
            ("label: 'Employment'",                f"label: {L}.uiEmploymentType"),
            ("label: 'Experience'",                f"label: {L}.uiExperienceLevel"),
            ("label: 'Start date'",                f"label: {L}.uiStartDate"),
            ("label: 'Company'",                   f"label: {L}.uiCompany"),
            ("label: 'Employment type'",           f"label: {L}.uiEmploymentType"),
            ("label: 'Experience level'",          f"label: {L}.uiExperienceLevel"),
            ("label: 'Paid status'",               f"label: {L}.uiPaidStatus"),
            ("label: 'Contact'",                   f"label: {L}.uiContact"),
            ("label: 'External link'",             f"label: {L}.uiExternalLink"),
            ("label: 'Attachments'",               f"label: {L}.uiAttachments"),
            ("title: 'Benefits'",                  f"title: {L}.uiBenefits"),
            ("title: 'Application Process'",       f"title: {L}.uiApplicationProcess"),
            ("title: 'Skills Needed'",             f"title: {L}.uiSkillsNeeded"),
            ("title: 'Additional Information'",    f"title: {L}.uiAdditionalInformation"),
            ("title: 'Tags'",                      f"title: {L}.uiTags"),
            ("title: 'External Application'",      f"title: {L}.uiExternalApplication"),
            ("label: 'Link'",                      f"label: {L}.uiLink"),
            ("label: 'Open Link'",                 f"label: {L}.uiOpenLink"),
        ],
    },
    # ─── internships_screen ────────────────────────────────────────────────────
    "lib/screens/student/internships_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Login required'",            f"title: {L}.uiLoginRequired"),
            ("title: 'Internships'",               f"title: {L}.uiInternships"),
            ("title: 'Featured Internships'",      f"title: {L}.uiFeaturedInternships"),
            ("title: 'Available Internships'",     f"title: {L}.uiAvailableInternships"),
            ("label: 'Unavailable'",               f"label: {L}.uiUnavailable"),
            ("label: 'Closed'",                    f"label: {L}.uiClosed"),
            ("label: 'Remote'",                    f"label: {L}.uiRemote"),
            ("label: 'Paid'",                      f"label: {L}.uiPaid"),
            ("label: 'Summer'",                    f"label: {L}.uiSummer"),
            ("label: 'Tech'",                      f"label: {L}.uiTech"),
            ("label: 'Marketing'",                 f"label: {L}.uiMarketing"),
        ],
    },
    # ─── jobs_screen ───────────────────────────────────────────────────────────
    "lib/screens/student/jobs_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Login required'",            f"title: {L}.uiLoginRequired"),
            ("title: 'Jobs'",                      f"title: {L}.uiJobs"),
            ("title: 'Categories'",                f"title: {L}.uiCategories"),
            ("title: 'Available Jobs'",            f"title: {L}.uiAvailableJobs"),
            ("label: 'Unavailable'",               f"label: {L}.uiUnavailable"),
            ("label: 'Closed'",                    f"label: {L}.uiClosed"),
            ("label: 'Tech'",                      f"label: {L}.uiTech"),
            ("label: 'Design'",                    f"label: {L}.uiDesign"),
            ("label: 'Business'",                  f"label: {L}.uiBusiness"),
            ("label: 'Legal'",                     f"label: {L}.uiLegal"),
            ("label: 'Marketing'",                 f"label: {L}.uiMarketing"),
            ("tooltip: 'Clear search'",            f"tooltip: {L}.uiClearSearch"),
        ],
    },
    # ─── trainings_screen ──────────────────────────────────────────────────────
    "lib/screens/student/trainings_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Link unavailable'",          f"title: {L}.uiLinkUnavailable"),
            ("title: 'Open unavailable'",          f"title: {L}.uiOpenUnavailable"),
            ("title: 'Login required'",            f"title: {L}.uiLoginRequired"),
            ("title: 'Training'",                  f"title: {L}.uiTraining"),
            ("subtitle: 'Courses, books, and certifications that sharpen your journey.'", f"subtitle: {L}.uiTrainingSubtitle"),
            ("tooltip: 'Saved resources'",         f"tooltip: {L}.uiSavedResources"),
            ("label: 'FREE'",                      f"label: {L}.uiFree.toUpperCase()"),
            ("label: 'CERTIFIED'",                 f"label: {L}.uiCertified.toUpperCase()"),
            ("label: 'FEATURED'",                  f"label: {L}.uiFeatured.toUpperCase()"),
            ("label: 'COURSE'",                    f"label: {L}.uiCourse.toUpperCase()"),
            ("label: 'VIDEO'",                     f"label: {L}.uiVideo.toUpperCase()"),
            ("label: 'BOOK'",                      f"label: {L}.uiBook.toUpperCase()"),
            ("label: 'GUIDE'",                     f"label: {L}.uiGuide.toUpperCase()"),
            ("label: 'PROGRAM'",                   f"label: {L}.uiProgram.toUpperCase()"),
            ("title: 'No training programs available right now'",  f"title: {L}.uiNoTrainingAvailableNow"),
            ("title: 'No training programs available in this topic'", f"title: {L}.uiNoTrainingInTopic"),
        ],
    },
    # ─── sponsored_opportunities_screen ────────────────────────────────────────
    "lib/screens/student/sponsored_opportunities_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Login required'",            f"title: {L}.uiLoginRequired"),
            ("title: 'Application blocked'",       f"title: {L}.uiApplicationBlocked"),
            ("title: 'CV required'",               f"title: {L}.uiCvRequired"),
            ("title: 'All Sponsored Programs'",    f"title: {L}.uiAllSponsoredPrograms"),
            ("title: 'Sponsored'",                 f"title: {L}.uiSponsored"),
            ("label: 'All'",                       f"label: {L}.uiAll"),
            ("label: 'Funding'",                   f"label: {L}.uiFunding"),
            ("label: 'Startup'",                   f"label: {L}.uiStartup"),
            ("label: 'Competition'",               f"label: {L}.uiCompetition"),
            ("label: 'Grants'",                    f"label: {L}.uiGrants"),
            ("label: 'Internships'",               f"label: {L}.uiInternships"),
            ("label: 'Unavailable'",               f"label: {L}.uiUnavailable"),
            ("label: 'Closed'",                    f"label: {L}.uiClosed"),
            ("label: 'Sponsored'",                 f"label: {L}.uiSponsored"),
            ("hintText: 'Search programs, partners...'", f"hintText: {L}.uiSearchPrograms"),
            ("tooltip: 'Clear search'",            f"tooltip: {L}.uiClearSearch"),
        ],
    },
    # ─── scholarships_screen ───────────────────────────────────────────────────
    "lib/screens/student/scholarships_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Scholarships'",              f"title: {L}.uiScholarships"),
            ("tooltip: 'Notifications'",           f"tooltip: {L}.uiNotifications"),
            ("tooltip: 'Saved scholarships'",      f"tooltip: {L}.uiSavedScholarships"),
        ],
    },
    # ─── scholarship_detail_screen ─────────────────────────────────────────────
    "lib/screens/student/scholarship_detail_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("label: 'Deadline'",                  f"label: {L}.uiDeadline"),
            ("label: 'Destination'",               f"label: {L}.uiDestination"),
            ("label: 'Provider'",                  f"label: {L}.uiProvider"),
            ("label: 'Support Type'",              f"label: {L}.uiSupportType"),
            ("label: 'Application deadline'",      f"label: {L}.uiApplicationDeadline"),
            ("label: 'Location'",                  f"label: {L}.uiLocation"),
            ("label: 'Funding type'",              f"label: {L}.uiFundingType"),
            ("label: 'Level'",                     f"label: {L}.uiLevel"),
            ("label: 'Category'",                  f"label: {L}.uiCategory"),
            ("title: 'Quick Snapshot'",            f"title: {L}.uiQuickSnapshot"),
            ("title: 'About This Scholarship'",    f"title: {L}.uiAboutThisScholarship"),
            ("title: 'Who Can Apply'",             f"title: {L}.uiWhoCanApply"),
            ("title: 'Scholarship Profile'",       f"title: {L}.uiScholarshipProfile"),
            ("title: 'Application Link'",          f"title: {L}.uiApplicationLink"),
        ],
    },
    # ─── idea_details_screen ───────────────────────────────────────────────────
    "lib/screens/student/idea_details_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("label: 'Creator'",                   f"label: {L}.uiCreator"),
            ("label: 'Last updated'",              f"label: {L}.uiLastUpdated"),
            ("label: 'Posted'",                    f"label: {L}.uiPosted"),
            ("label: 'Stage'",                     f"label: {L}.uiStage"),
            ("label: 'Status'",                    f"label: {L}.uiStatus"),
            ("label: 'Category'",                  f"label: {L}.uiCategory"),
            ("label: 'Level'",                     f"label: {L}.uiLevel"),
            ("label: 'Sparks'",                    f"label: {L}.uiSparks"),
            ("label: 'Interested'",                f"label: {L}.uiInterested"),
            ("label: 'Views'",                     f"label: {L}.uiViews"),
            ("title: 'Overview'",                  f"title: {L}.uiOverview"),
            ("title: 'Full Description'",          f"title: {L}.uiFullDescription"),
            ("title: 'Problem Statement'",         f"title: {L}.uiProblemStatement"),
            ("title: 'Proposed Solution'",         f"title: {L}.uiProposedSolution"),
            ("title: 'Audience And Impact'",       f"title: {L}.uiAudienceAndImpact"),
            ("label: 'Target audience'",           f"label: {L}.uiTargetAudience"),
            ("label: 'Benefits and impact'",       f"label: {L}.uiBenefitsAndImpact"),
            ("title: 'Collaboration Needs'",       f"title: {L}.uiCollaborationNeeds"),
            ("title: 'Team needed'",               f"title: {L}.uiTeamNeeded"),
            ("title: 'Skills needed'",             f"title: {L}.uiSkillsNeeded"),
            ("label: 'Tools and stack'",           f"label: {L}.uiToolsAndStack"),
            ("label: 'Resources or needs'",        f"label: {L}.uiResourcesOrNeeds"),
            ("title: 'References And Links'",      f"title: {L}.uiReferencesAndLinks"),
            ("label: 'Attachment'",                f"label: {L}.uiAttachment"),
            ("label: 'Open Attachment'",           f"label: {L}.uiOpenAttachment"),
            ("title: 'Tags'",                      f"title: {L}.uiTags"),
            ("title: 'Update unavailable'",        f"title: {L}.uiUpdateUnavailable"),
            ("title: 'Open unavailable'",          f"title: {L}.uiOpenUnavailable"),
            ("title: 'Interest Snapshot'",         f"title: {L}.uiInterestSnapshot"),
            ("title: 'Open Roles'",                f"title: {L}.uiOpenRoles"),
            ("title: 'Roles'",                     f"title: {L}.uiRoles"),
            ("title: 'Key Skills'",                f"title: {L}.uiKeySkills"),
            ("title: 'Skills'",                    f"title: {L}.uiSkills"),
            ("tooltip: 'Share idea'",              f"tooltip: {L}.uiShareIdea"),
        ],
    },
    # ─── project_ideas_screen ──────────────────────────────────────────────────
    "lib/screens/student/project_ideas_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Update unavailable'",        f"title: {L}.uiUpdateUnavailable"),
            ("title: 'No ideas match this view'",  f"title: {L}.uiNoIdeasMatchView"),
            ("subtitle: 'Try a different filter or start a new idea.'", f"subtitle: {L}.uiTryDifferentFilter"),
            ("title: 'No ideas yet'",              f"title: {L}.uiNoIdeasYet"),
            ("subtitle: 'Create your first idea or adjust the filters.'", f"subtitle: {L}.uiCreateFirstIdea"),
            ("label: 'Ideas'",                     f"label: {L}.uiIdeas"),
            ("label: 'Interested'",                f"label: {L}.uiInterested"),
        ],
    },
    # ─── create_idea_screen ────────────────────────────────────────────────────
    "lib/screens/student/create_idea_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Upload in progress'",        f"title: {L}.uiUploadInProgress"),
            ("title: 'Submission unavailable'",    f"title: {L}.uiSubmissionUnavailable"),
            ("title: 'Select category'",           f"title: {L}.uiSelectCategory"),
            ("title: 'Select stage'",              f"title: {L}.uiSelectStage"),
            ("title: 'Upload unavailable'",        f"title: {L}.uiUploadUnavailable"),
            ("title: 'Login required'",            f"title: {L}.uiLoginRequired"),
            ("title: 'Upload complete'",           f"title: {L}.uiUploadComplete"),
            ("title: 'Publish'",                   f"title: {L}.uiPublish"),
            ("label: 'Visible'",                   f"label: {L}.uiVisible"),
            ("subtitle: 'Show in discovery'",      f"subtitle: {L}.uiShowInDiscovery"),
            ("label: 'Hidden'",                    f"label: {L}.uiHiddenLabel"),
            ("subtitle: 'Keep out of discovery'",  f"subtitle: {L}.uiKeepOutOfDiscovery"),
            ("title: 'Idea Basics'",               f"title: {L}.uiIdeaBasics"),
            ("label: 'Idea Title'",                f"label: {L}.uiIdeaTitle"),
            ("label: 'Short Tagline'",             f"label: {L}.uiShortTagline"),
            ("title: 'Category'",                  f"title: {L}.uiCategory"),
            ("title: 'Stage'",                     f"title: {L}.uiStage"),
            ("label: 'Best suited for'",           f"label: {L}.uiBestSuitedFor"),
            ("title: 'Idea Description'",          f"title: {L}.uiIdeaDescription"),
            ("label: 'Idea Overview'",             f"label: {L}.uiIdeaOverview"),
            ("label: 'Problem Statement'",         f"label: {L}.uiProblemStatement"),
            ("label: 'Solution'",                  f"label: {L}.uiSolution"),
            ("label: 'Target Audience'",           f"label: {L}.uiTargetAudience"),
            ("label: 'Benefits / Impact'",         f"label: {L}.uiBenefitsAndImpact"),
            ("title: 'Collaboration'",             f"title: {L}.uiCollaboration"),
            ("title: 'Team Needed'",               f"title: {L}.uiTeamNeeded"),
            ("title: 'Skills Needed'",             f"title: {L}.uiSkillsNeeded"),
            ("label: 'Resources / Needs'",         f"label: {L}.uiResourcesNeeds"),
            ("title: 'Optional Extras'",           f"title: {L}.uiOptionalExtras"),
            ("label: 'Deck / Demo Link'",          f"label: {L}.uiDeckDemoLink"),
            ("label: 'Visibility'",                f"label: {L}.uiVisibility"),
            ("label: 'Focus'",                     f"label: {L}.uiFocus"),
            ("title: 'Editing locked'",            f"title: {L}.uiEditingLocked"),
        ],
    },
    # ─── edit_profile_screen ───────────────────────────────────────────────────
    "lib/screens/student/edit_profile_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Profile updated'",           f"title: {L}.uiProfileUpdated"),
            ("title: 'Avatar unavailable'",        f"title: {L}.uiAvatarUnavailable"),
            ("title: 'Photo unavailable'",         f"title: {L}.uiPhotoUnavailable"),
            ("title: 'Upload unavailable'",        f"title: {L}.uiUploadUnavailable"),
            ("title: 'Remove unavailable'",        f"title: {L}.uiRemoveUnavailable"),
            ("title: 'Update unavailable'",        f"title: {L}.uiUpdateUnavailable"),
            ("title: 'Edit Profile'",              f"title: {L}.uiEditProfile"),
            ("label: 'Choose Avatar'",             f"label: {L}.uiChooseAvatar"),
            ("label: 'Upload Photo'",              f"label: {L}.uiUploadPhoto"),
            ("label: 'Use Uploaded'",              f"label: {L}.uiUseUploaded"),
            ("label: 'Remove Photo'",              f"label: {L}.uiRemovePhoto"),
            ("title: 'Basic Details'",             f"title: {L}.uiBasicDetails"),
            ("label: 'Full Name'",                 f"label: {L}.uiFullName"),
            ("label: 'Email'",                     f"label: {L}.uiEmail"),
            ("label: 'Phone'",                     f"label: {L}.uiPhone"),
            ("label: 'Location'",                  f"label: {L}.uiLocation"),
            ("title: 'Academic Profile'",          f"title: {L}.uiAcademicProfile"),
            ("label: 'University'",                f"label: {L}.uiUniversity"),
            ("label: 'Field of Study'",            f"label: {L}.uiFieldOfStudy"),
            ("label: 'Bio'",                       f"label: {L}.uiBio"),
        ],
    },
    # ─── profile_screen ────────────────────────────────────────────────────────
    "lib/screens/student/profile_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("label: 'Email'",                     f"label: {L}.uiEmail"),
            ("label: 'Phone'",                     f"label: {L}.uiPhone"),
            ("label: 'Location'",                  f"label: {L}.uiLocation"),
            ("label: 'Academic Level'",            f"label: {L}.uiAcademicLevel80Cc"),
            ("label: 'University'",                f"label: {L}.uiUniversity"),
            ("label: 'Field of Study'",            f"label: {L}.uiFieldOfStudy"),
            ("label: 'Profile strength'",          f"label: {L}.uiProfileStrength"),
            ("label: 'Saved'",                     f"label: {L}.uiSaved"),
            ("label: 'Applied'",                   f"label: {L}.uiApplied"),
            ("label: 'CV Studio'",                 f"label: {L}.uiCvStudio"),
            ("label: 'Alerts'",                    f"label: {L}.uiAlerts"),
            ("label: 'Edit profile'",              f"label: {L}.uiEditProfile"),
            ("label: 'Open CV Studio'",            f"label: {L}.uiOpenCvStudio"),
            ("label: 'Edit Profile'",              f"label: {L}.uiEditProfile"),
            ("label: 'Student snapshot'",          f"label: {L}.uiStudentSnapshot"),
            ("label: 'Edit'",                      f"label: {L}.uiEdit"),
            ("label: 'Student toolkit'",           f"label: {L}.uiStudentToolkit"),
            ("title: 'CV Studio'",                 f"title: {L}.uiCvStudio"),
            ("subtitle: 'Build, upload, and export your CV.'", f"subtitle: {L}.uiCvStudioSubtitle"),
            ("title: 'Saved collection'",          f"title: {L}.uiSavedCollection"),
            ("subtitle: 'Jump back into everything you bookmarked.'", f"subtitle: {L}.uiJumpBackBookmarked"),
            ("title: 'Notifications'",             f"title: {L}.uiNotifications"),
            ("title: 'Settings'",                  f"title: {L}.uiSettings"),
            ("subtitle: 'Preferences, display, and app choices.'", f"subtitle: {L}.uiSettingsSubtitle"),
            ("title: 'Security & privacy'",        f"title: {L}.uiSecurityPrivacy"),
            ("subtitle: 'Password and account protection.'", f"subtitle: {L}.uiSecuritySubtitle"),
            ("title: 'Help center'",               f"title: {L}.uiHelpCenter"),
            ("subtitle: 'Answers, guidance, and support.'", f"subtitle: {L}.uiHelpCenterSubtitle"),
            ("title: 'About FutureGate'",          f"title: {L}.uiAboutFutureGate"),
            ("subtitle: 'Learn more about the platform.'", f"subtitle: {L}.uiAboutSubtitle"),
            ("title: 'Sign out'",                  f"title: {L}.signOutTitle"),
            ("subtitle: 'End this session on the current device.'", f"subtitle: {L}.uiSignOutSubtitle"),
        ],
    },
    # ─── cv_screen ─────────────────────────────────────────────────────────────
    "lib/screens/student/cv_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Content needed'",            f"title: {L}.uiContentNeeded"),
            ("title: 'Upload unavailable'",        f"title: {L}.uiUploadUnavailable"),
            ("title: 'Preview unavailable'",       f"title: {L}.uiPreviewUnavailable"),
            ("title: 'Open unavailable'",          f"title: {L}.uiOpenUnavailable"),
            ("title: 'Document unavailable'",      f"title: {L}.uiDocumentUnavailable"),
            ("title: 'My CV'",                     f"title: {L}.uiMyCv"),
            ("label: 'Preview'",                   f"label: {L}.uiPreview"),
            ("label: 'Uploaded CV'",               f"label: {L}.uiUploadedCv"),
        ],
    },
    # ─── cv_edit_screen ────────────────────────────────────────────────────────
    "lib/screens/student/cv_edit_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'CV saved'",                  f"title: {L}.uiCvSaved"),
            ("title: 'Save unavailable'",          f"title: {L}.uiSaveUnavailable"),
            ("label: 'Degree'",                    f"label: {L}.uiDegree"),
            ("label: 'Institution'",               f"label: {L}.uiInstitution"),
            ("label: 'Year'",                      f"label: {L}.uiYear"),
            ("label: 'Position'",                  f"label: {L}.uiPosition"),
            ("label: 'Company'",                   f"label: {L}.uiCompany"),
            ("label: 'Duration'",                  f"label: {L}.uiDuration"),
            ("title: 'Edit CV'",                   f"title: {L}.uiEditCv"),
            ("title: 'Personal Information'",      f"title: {L}.uiPersonalInformation"),
            ("label: 'Full Name'",                 f"label: {L}.uiFullName"),
            ("label: 'Email'",                     f"label: {L}.uiEmail"),
            ("label: 'Phone'",                     f"label: {L}.uiPhone"),
            ("label: 'Address'",                   f"label: {L}.uiAddress"),
            ("title: 'Professional Summary'",      f"title: {L}.uiProfessionalSummary"),
            ("label: 'A brief summary of your profile'", f"label: {L}.uiBriefSummary"),
            ("title: 'Education'",                 f"title: {L}.uiEducation"),
            ("title: 'Experience'",                f"title: {L}.uiExperience"),
            ("title: 'Skills'",                    f"title: {L}.uiSkills"),
            ("label: 'Add a skill'",               f"label: {L}.uiAddSkill"),
            ("title: 'Languages'",                 f"title: {L}.uiLanguages"),
            ("label: 'Add a language'",            f"label: {L}.uiAddALanguage"),
            ("label: 'Save CV'",                   f"label: {L}.uiSaveCv"),
        ],
    },
    # ─── cv_preview_screen ─────────────────────────────────────────────────────
    "lib/screens/student/cv_preview_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Export complete'",           f"title: {L}.uiExportComplete"),
            ("title: 'Export unavailable'",        f"title: {L}.uiExportUnavailable"),
            ("title: 'Preview unavailable'",       f"title: {L}.uiPreviewUnavailable"),
            ("title: 'CV Preview'",                f"title: {L}.uiCvPreview"),
            ("subtitle: 'Review the final layout before you export or share it.'", f"subtitle: {L}.uiCvPreviewSubtitle"),
            ("tooltip: 'Share PDF'",               f"tooltip: {L}.uiSharePdf"),
            ("label: 'Export & Save CV'",          f"label: {L}.uiExportSaveCv"),
        ],
    },
    # ─── cv_template_selector_screen ───────────────────────────────────────────
    "lib/screens/student/cv_template_selector_screen.dart": {
        "import": IMP, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("title: 'Choose Template'",           f"title: {L}.uiChooseTemplate"),
            ("subtitle: 'Pick the resume style that best fits the role you want.'", f"subtitle: {L}.uiChooseTemplateSubtitle"),
            ("tooltip: 'Apply template'",          f"tooltip: {L}.uiApplyTemplate"),
        ],
    },
    # ─── student workspace shell ────────────────────────────────────────────────
    "lib/widgets/student/student_workspace_shell.dart": {
        "import": IMP1, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("tooltip: 'Saved items'",             f"tooltip: {L}.uiSavedItems"),
            ("tooltip: 'Applied opportunities'",   f"tooltip: {L}.uiAppliedOpportunities"),
            ("message: 'Profile'",                 f"message: {L}.uiProfile"),
        ],
    },
    # ─── chat widgets ──────────────────────────────────────────────────────────
    "lib/widgets/chat/chat_message_bubble.dart": {
        "import": "import '../../l10n/generated/app_localizations.dart';",
        "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("label: 'Edit message'",              f"label: {L}.uiEditMessage"),
            ("label: 'Delete for everyone'",       f"label: {L}.uiDeleteForEveryone"),
            ("title: 'Attachment unavailable'",    f"title: {L}.uiAttachmentUnavailable"),
        ],
    },
    "lib/widgets/chat/chat_input_bar.dart": {
        "import": "import '../../l10n/generated/app_localizations.dart';",
        "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("label: 'Editing message'",           f"label: {L}.uiEditingMessage"),
            ("label: 'Formalize'",                 f"label: {L}.uiFormalize"),
            ("label: 'Correct'",                   f"label: {L}.uiCorrect"),
            ("label: 'Translate'",                 f"label: {L}.uiTranslate"),
            ("tooltip: 'Attach'",                  f"tooltip: {L}.uiAttach"),
        ],
    },
    "lib/widgets/chat/chat_confirmation_dialog.dart": {
        "import": "import '../../l10n/generated/app_localizations.dart';",
        "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("label: 'Cancel'",                    f"label: {L}.cancelLabel"),
        ],
    },
    "lib/widgets/chat/conversation_list_item.dart": {
        "import": "import '../../l10n/generated/app_localizations.dart';",
        "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("label: 'Muted'",                     f"label: {L}.uiMuted"),
            ("label: 'Archived'",                  f"label: {L}.uiArchived"),
        ],
    },
    # ─── idea widgets ──────────────────────────────────────────────────────────
    "lib/widgets/ideas/idea_cards.dart": {
        "import": IMP1, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("label: 'View'",                      f"label: {L}.uiView"),
            ("label: 'Edit'",                      f"label: {L}.uiEdit"),
            ("label: 'Team'",                      f"label: {L}.uiTeam"),
        ],
    },
    "lib/widgets/ideas/my_ideas_toggle.dart": {
        "import": IMP1, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("label: 'Discover'",                  f"label: {L}.uiDiscover"),
            ("label: 'My Ideas'",                  f"label: {L}.uiMyIdeas"),
        ],
    },
    # ─── training widgets ──────────────────────────────────────────────────────
    "lib/widgets/training_programs_widgets.dart": {
        "import": IMP1, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("hintText: 'Search for courses...'",  f"hintText: {L}.uiSearchCourses"),
            ("tooltip: 'Clear search'",            f"tooltip: {L}.uiClearSearch"),
            ("tooltip: 'Training menu'",           f"tooltip: {L}.uiTrainingMenu"),
            ("tooltip: 'Focus search'",            f"tooltip: {L}.uiFocusSearch"),
            ("label: 'VIDEO'",                     f"label: {L}.uiVideo.toUpperCase()"),
            ("label: 'BOOK'",                      f"label: {L}.uiBook.toUpperCase()"),
            ("label: 'GUIDE'",                     f"label: {L}.uiGuide.toUpperCase()"),
            ("label: 'COURSE'",                    f"label: {L}.uiCourse.toUpperCase()"),
            ("label: 'TRAIN'",                     f"label: {L}.uiTrain.toUpperCase()"),
        ],
    },
    "lib/widgets/training_resource_card.dart": {
        "import": IMP1, "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("label: 'FEATURED'",                  f"label: {L}.uiFeatured.toUpperCase()"),
        ],
    },
    # ─── company workspace shell ────────────────────────────────────────────────
    "lib/widgets/company/company_workspace_shell.dart": {
        "import": "import '../../l10n/generated/app_localizations.dart';",
        "after": "import 'package:flutter/material.dart';",
        "replacements": [
            ("tooltip: 'Notifications'",           f"tooltip: {L}.uiNotifications"),
            ("message: 'Company profile'",         f"message: {L}.uiCompanyProfile"),
        ],
    },
}

# Additional keys needed — check and add ARB if missing
EXTRA_EN = {
    'uiInternshipsSubtitle': 'Hands-on student placements',
    'uiSponsoredSubtitle': 'Partner-backed support',
    'uiTrendingOpportunities': 'Trending Opportunities',
    'uiLatestOpportunities': 'Latest Opportunities',
    'uiFilterOpportunities': 'Filter opportunities',
    'uiFeaturedInternships': 'Featured Internships',
    'uiAvailableInternships': 'Available Internships',
    'uiAvailableJobs': 'Available Jobs',
    'uiCategories': 'Categories',
    'uiSummer': 'Summer',
    'uiTech': 'Tech',
    'uiMarketing': 'Marketing',
    'uiDesign': 'Design',
    'uiBusiness': 'Business',
    'uiLegal': 'Legal',
    'uiFunding': 'Funding',
    'uiStartup': 'Startup',
    'uiCompetition': 'Competition',
    'uiGrants': 'Grants',
    'uiSavedScholarships': 'Saved scholarships',
    'uiDestination': 'Destination',
    'uiSupportType': 'Support Type',
    'uiCreator': 'Creator',
    'uiLastUpdated': 'Last updated',
    'uiPosted': 'Posted',
    'uiStage': 'Stage',
    'uiSparks': 'Sparks',
    'uiInterested': 'Interested',
    'uiViews': 'Views',
    'uiOverview': 'Overview',
    'uiFullDescription': 'Full Description',
    'uiAudienceAndImpact': 'Audience And Impact',
    'uiCollaborationNeeds': 'Collaboration Needs',
    'uiTargetAudience': 'Target Audience',
    'uiBenefitsAndImpact': 'Benefits And Impact',
    'uiToolsAndStack': 'Tools And Stack',
    'uiResourcesOrNeeds': 'Resources Or Needs',
    'uiReferencesAndLinks': 'References And Links',
    'uiAttachment': 'Attachment',
    'uiOpenAttachment': 'Open Attachment',
    'uiInterestSnapshot': 'Interest Snapshot',
    'uiOpenRoles': 'Open Roles',
    'uiKeySkills': 'Key Skills',
    'uiShareOpportunity': 'Share opportunity',
    'uiShareIdea': 'Share idea',
    'uiSharePdf': 'Share PDF',
    'uiTryDifferentFilter': 'Try a different filter or start a new idea.',
    'uiCreateFirstIdea': 'Create your first idea or adjust the filters.',
    'uiUploadComplete': 'Upload complete',
    'uiVisible': 'Visible',
    'uiShowInDiscovery': 'Show in discovery',
    'uiKeepOutOfDiscovery': 'Keep out of discovery',
    'uiIdeaBasics': 'Idea Basics',
    'uiIdeaTitle': 'Idea Title',
    'uiShortTagline': 'Short Tagline',
    'uiIdeaDescription': 'Idea Description',
    'uiIdeaOverview': 'Idea Overview',
    'uiSolution': 'Solution',
    'uiCollaboration': 'Collaboration',
    'uiTeamNeeded': 'Team Needed',
    'uiResourcesNeeds': 'Resources / Needs',
    'uiOptionalExtras': 'Optional Extras',
    'uiDeckDemoLink': 'Deck / Demo Link',
    'uiVisibility': 'Visibility',
    'uiFocus': 'Focus',
    'uiBestSuitedFor': 'Best suited for',
    'uiProfileUpdated': 'Profile updated',
    'uiAvatarUnavailable': 'Avatar unavailable',
    'uiPhotoUnavailable': 'Photo unavailable',
    'uiRemoveUnavailable': 'Remove unavailable',
    'uiBasicDetails': 'Basic Details',
    'uiFullName': 'Full Name',
    'uiAddress': 'Address',
    'uiBio': 'Bio',
    'uiProfileStrength': 'Profile strength',
    'uiStudentSnapshot': 'Student snapshot',
    'uiStudentToolkit': 'Student toolkit',
    'uiCvStudio': 'CV Studio',
    'uiCvStudioSubtitle': 'Build, upload, and export your CV.',
    'uiSavedCollection': 'Saved collection',
    'uiSecurityPrivacy': 'Security & privacy',
    'uiHelpCenter': 'Help center',
    'uiContentNeeded': 'Content needed',
    'uiDocumentUnavailable': 'Document unavailable',
    'uiMyCv': 'My CV',
    'uiUploadedCv': 'Uploaded CV',
    'uiCvSaved': 'CV saved',
    'uiSaveUnavailable': 'Save unavailable',
    'uiDegree': 'Degree',
    'uiInstitution': 'Institution',
    'uiYear': 'Year',
    'uiPosition': 'Position',
    'uiProfessionalSummary': 'Professional Summary',
    'uiEducation': 'Education',
    'uiExportComplete': 'Export complete',
    'uiExportUnavailable': 'Export unavailable',
    'uiCvPreview': 'CV Preview',
    'uiChooseTemplate': 'Choose Template',
    'uiSavedItems': 'Saved items',
    'uiAppliedOpportunities': 'Applied opportunities',
    'uiCompanyProfile': 'Company profile',
    'uiRefreshApplications': 'Refresh applications',
    'uiRefreshSavedItems': 'Refresh saved items',
    'uiOpps': 'Opps',
    'uiClearSearch': 'Clear search',
    'uiTrainingMenu': 'Training menu',
    'uiSavedResources': 'Saved resources',
    'uiTrainingSubtitle': 'Courses, books, and certifications that sharpen your journey.',
    'uiEditingMessage': 'Editing message',
    'uiDeleteForEveryone': 'Delete for everyone',
    'uiMuted': 'Muted',
    'uiArchived': 'Archived',
    'uiAttach': 'Attach',
    'uiMyIdeas': 'My Ideas',
    'uiAttachmentUnavailable': 'Attachment unavailable',
    'uiChatUnavailable': 'Chat unavailable',
    'uiScholarshipUnavailable': 'Scholarship unavailable',
    'uiOpportunityUnavailable': 'Opportunity unavailable',
    'uiApplicationBlocked': 'Application blocked',
    'uiCvRequired': 'CV required',
    'uiAllSponsoredPrograms': 'All Sponsored Programs',
    'uiPaidOnly': 'Paid only',
    'uiOpenLink': 'Open Link',
    'uiContact': 'Contact',
    'uiExternalLink': 'External link',
    'uiAttachments': 'Attachments',
    'uiBenefits': 'Benefits',
    'uiApplicationProcess': 'Application Process',
    'uiSkillsNeeded': 'Skills Needed',
    'uiAdditionalInformation': 'Additional Information',
    'uiExternalApplication': 'External Application',
    'uiLink': 'Link',
    'uiExperienceLevel': 'Experience level',
    'uiStartDate': 'Start date',
    'uiLocation': 'Location',
    'uiType': 'Type',
}

EXTRA_FR = {
    'uiInternshipsSubtitle': 'Stages pratiques pour étudiants',
    'uiSponsoredSubtitle': 'Soutien partenaire',
    'uiTrendingOpportunities': 'Opportunités tendance',
    'uiLatestOpportunities': 'Dernières opportunités',
    'uiFilterOpportunities': 'Filtrer les opportunités',
    'uiFeaturedInternships': 'Stages en vedette',
    'uiAvailableInternships': 'Stages disponibles',
    'uiAvailableJobs': 'Emplois disponibles',
    'uiCategories': 'Catégories',
    'uiSummer': 'Été',
    'uiTech': 'Tech',
    'uiMarketing': 'Marketing',
    'uiDesign': 'Design',
    'uiBusiness': 'Commerce',
    'uiLegal': 'Juridique',
    'uiFunding': 'Financement',
    'uiStartup': 'Startup',
    'uiCompetition': 'Concours',
    'uiGrants': 'Subventions',
    'uiSavedScholarships': 'Bourses sauvegardées',
    'uiDestination': 'Destination',
    'uiSupportType': 'Type de soutien',
    'uiCreator': 'Créateur',
    'uiLastUpdated': 'Dernière mise à jour',
    'uiPosted': 'Publié',
    'uiStage': 'Étape',
    'uiSparks': 'Étincelles',
    'uiInterested': 'Intéressés',
    'uiViews': 'Vues',
    'uiOverview': 'Aperçu',
    'uiFullDescription': 'Description complète',
    'uiAudienceAndImpact': 'Public et impact',
    'uiCollaborationNeeds': 'Besoins de collaboration',
    'uiTargetAudience': 'Public cible',
    'uiBenefitsAndImpact': 'Avantages et impact',
    'uiToolsAndStack': 'Outils et stack',
    'uiResourcesOrNeeds': 'Ressources ou besoins',
    'uiReferencesAndLinks': 'Références et liens',
    'uiAttachment': 'Pièce jointe',
    'uiOpenAttachment': 'Ouvrir la pièce jointe',
    'uiInterestSnapshot': 'Aperçu des intérêts',
    'uiOpenRoles': 'Rôles ouverts',
    'uiKeySkills': 'Compétences clés',
    'uiShareOpportunity': "Partager l'opportunité",
    'uiShareIdea': "Partager l'idée",
    'uiSharePdf': 'Partager le PDF',
    'uiTryDifferentFilter': 'Essayez un autre filtre ou créez une nouvelle idée.',
    'uiCreateFirstIdea': 'Créez votre première idée ou ajustez les filtres.',
    'uiUploadComplete': 'Téléversement terminé',
    'uiVisible': 'Visible',
    'uiShowInDiscovery': 'Afficher dans la découverte',
    'uiKeepOutOfDiscovery': 'Garder hors de la découverte',
    'uiIdeaBasics': 'Bases de l\'idée',
    'uiIdeaTitle': 'Titre de l\'idée',
    'uiShortTagline': 'Accroche courte',
    'uiIdeaDescription': 'Description de l\'idée',
    'uiIdeaOverview': 'Aperçu de l\'idée',
    'uiSolution': 'Solution',
    'uiCollaboration': 'Collaboration',
    'uiTeamNeeded': 'Équipe nécessaire',
    'uiResourcesNeeds': 'Ressources / Besoins',
    'uiOptionalExtras': 'Extras optionnels',
    'uiDeckDemoLink': 'Lien Deck / Démo',
    'uiVisibility': 'Visibilité',
    'uiFocus': 'Focus',
    'uiBestSuitedFor': 'Mieux adapté pour',
    'uiProfileUpdated': 'Profil mis à jour',
    'uiAvatarUnavailable': 'Avatar indisponible',
    'uiPhotoUnavailable': 'Photo indisponible',
    'uiRemoveUnavailable': 'Suppression indisponible',
    'uiBasicDetails': 'Informations de base',
    'uiFullName': 'Nom complet',
    'uiAddress': 'Adresse',
    'uiBio': 'Bio',
    'uiProfileStrength': 'Force du profil',
    'uiStudentSnapshot': 'Aperçu étudiant',
    'uiStudentToolkit': 'Boîte à outils étudiant',
    'uiCvStudio': 'Studio CV',
    'uiCvStudioSubtitle': 'Créez, téléversez et exportez votre CV.',
    'uiSavedCollection': 'Collection sauvegardée',
    'uiSecurityPrivacy': 'Sécurité et confidentialité',
    'uiHelpCenter': 'Centre d\'aide',
    'uiContentNeeded': 'Contenu requis',
    'uiDocumentUnavailable': 'Document indisponible',
    'uiMyCv': 'Mon CV',
    'uiUploadedCv': 'CV téléversé',
    'uiCvSaved': 'CV sauvegardé',
    'uiSaveUnavailable': 'Sauvegarde indisponible',
    'uiDegree': 'Diplôme',
    'uiInstitution': 'Établissement',
    'uiYear': 'Année',
    'uiPosition': 'Poste',
    'uiProfessionalSummary': 'Résumé professionnel',
    'uiEducation': 'Formation',
    'uiExportComplete': 'Export terminé',
    'uiExportUnavailable': 'Export indisponible',
    'uiCvPreview': 'Aperçu CV',
    'uiChooseTemplate': 'Choisir un modèle',
    'uiSavedItems': 'Éléments sauvegardés',
    'uiAppliedOpportunities': 'Candidatures',
    'uiCompanyProfile': 'Profil entreprise',
    'uiRefreshApplications': 'Actualiser les candidatures',
    'uiRefreshSavedItems': 'Actualiser les éléments',
    'uiOpps': 'Opps',
    'uiClearSearch': 'Effacer la recherche',
    'uiTrainingMenu': 'Menu formation',
    'uiSavedResources': 'Ressources sauvegardées',
    'uiTrainingSubtitle': 'Cours, livres et certifications pour développer votre parcours.',
    'uiEditingMessage': 'Modification du message',
    'uiDeleteForEveryone': 'Supprimer pour tous',
    'uiMuted': 'Silencieux',
    'uiArchived': 'Archivé',
    'uiAttach': 'Joindre',
    'uiMyIdeas': 'Mes idées',
    'uiAttachmentUnavailable': 'Pièce jointe indisponible',
    'uiChatUnavailable': 'Chat indisponible',
    'uiScholarshipUnavailable': 'Bourse indisponible',
    'uiOpportunityUnavailable': 'Opportunité indisponible',
    'uiApplicationBlocked': 'Candidature bloquée',
    'uiCvRequired': 'CV requis',
    'uiAllSponsoredPrograms': 'Tous les programmes sponsorisés',
    'uiPaidOnly': 'Rémunéré uniquement',
    'uiOpenLink': 'Ouvrir le lien',
    'uiContact': 'Contact',
    'uiExternalLink': 'Lien externe',
    'uiAttachments': 'Pièces jointes',
    'uiBenefits': 'Avantages',
    'uiApplicationProcess': 'Processus de candidature',
    'uiSkillsNeeded': 'Compétences requises',
    'uiAdditionalInformation': 'Informations supplémentaires',
    'uiExternalApplication': 'Candidature externe',
    'uiLink': 'Lien',
    'uiExperienceLevel': 'Niveau d\'expérience',
    'uiStartDate': 'Date de début',
    'uiLocation': 'Lieu',
    'uiType': 'Type',
}

EXTRA_AR = {
    'uiInternshipsSubtitle': 'تدريبات عملية للطلاب',
    'uiSponsoredSubtitle': 'دعم شراكات',
    'uiTrendingOpportunities': 'الفرص الرائجة',
    'uiLatestOpportunities': 'أحدث الفرص',
    'uiFilterOpportunities': 'تصفية الفرص',
    'uiFeaturedInternships': 'التدريبات المميزة',
    'uiAvailableInternships': 'التدريبات المتاحة',
    'uiAvailableJobs': 'الوظائف المتاحة',
    'uiCategories': 'الفئات',
    'uiSummer': 'صيفي',
    'uiTech': 'تقنية',
    'uiMarketing': 'تسويق',
    'uiDesign': 'تصميم',
    'uiBusiness': 'أعمال',
    'uiLegal': 'قانوني',
    'uiFunding': 'تمويل',
    'uiStartup': 'شركة ناشئة',
    'uiCompetition': 'مسابقة',
    'uiGrants': 'منح',
    'uiSavedScholarships': 'المنح المحفوظة',
    'uiDestination': 'الوجهة',
    'uiSupportType': 'نوع الدعم',
    'uiCreator': 'المنشئ',
    'uiLastUpdated': 'آخر تحديث',
    'uiPosted': 'تاريخ النشر',
    'uiStage': 'المرحلة',
    'uiSparks': 'إعجابات',
    'uiInterested': 'مهتم',
    'uiViews': 'مشاهدات',
    'uiOverview': 'نظرة عامة',
    'uiFullDescription': 'الوصف الكامل',
    'uiAudienceAndImpact': 'الجمهور والتأثير',
    'uiCollaborationNeeds': 'احتياجات التعاون',
    'uiTargetAudience': 'الجمهور المستهدف',
    'uiBenefitsAndImpact': 'الفوائد والتأثير',
    'uiToolsAndStack': 'الأدوات والتقنيات',
    'uiResourcesOrNeeds': 'الموارد أو الاحتياجات',
    'uiReferencesAndLinks': 'المراجع والروابط',
    'uiAttachment': 'مرفق',
    'uiOpenAttachment': 'فتح المرفق',
    'uiInterestSnapshot': 'ملخص الاهتمام',
    'uiOpenRoles': 'الأدوار المفتوحة',
    'uiKeySkills': 'المهارات الرئيسية',
    'uiShareOpportunity': 'مشاركة الفرصة',
    'uiShareIdea': 'مشاركة الفكرة',
    'uiSharePdf': 'مشاركة PDF',
    'uiTryDifferentFilter': 'جرب فلتراً مختلفاً أو ابدأ فكرة جديدة.',
    'uiCreateFirstIdea': 'أنشئ فكرتك الأولى أو اضبط الفلاتر.',
    'uiUploadComplete': 'اكتمل التحميل',
    'uiVisible': 'مرئي',
    'uiShowInDiscovery': 'إظهار في الاستكشاف',
    'uiKeepOutOfDiscovery': 'إخفاء من الاستكشاف',
    'uiIdeaBasics': 'أساسيات الفكرة',
    'uiIdeaTitle': 'عنوان الفكرة',
    'uiShortTagline': 'شعار قصير',
    'uiIdeaDescription': 'وصف الفكرة',
    'uiIdeaOverview': 'نظرة عامة على الفكرة',
    'uiSolution': 'الحل',
    'uiCollaboration': 'تعاون',
    'uiTeamNeeded': 'الفريق المطلوب',
    'uiResourcesNeeds': 'الموارد / الاحتياجات',
    'uiOptionalExtras': 'إضافات اختيارية',
    'uiDeckDemoLink': 'رابط العرض / الديمو',
    'uiVisibility': 'الظهور',
    'uiFocus': 'التركيز',
    'uiBestSuitedFor': 'الأنسب لـ',
    'uiProfileUpdated': 'تم تحديث الملف الشخصي',
    'uiAvatarUnavailable': 'الصورة الرمزية غير متاحة',
    'uiPhotoUnavailable': 'الصورة غير متاحة',
    'uiRemoveUnavailable': 'الحذف غير متاح',
    'uiBasicDetails': 'التفاصيل الأساسية',
    'uiFullName': 'الاسم الكامل',
    'uiAddress': 'العنوان',
    'uiBio': 'نبذة',
    'uiProfileStrength': 'قوة الملف الشخصي',
    'uiStudentSnapshot': 'ملخص الطالب',
    'uiStudentToolkit': 'أدوات الطالب',
    'uiCvStudio': 'استوديو السيرة الذاتية',
    'uiCvStudioSubtitle': 'أنشئ سيرتك الذاتية وحمّلها وصدّرها.',
    'uiSavedCollection': 'المجموعة المحفوظة',
    'uiSecurityPrivacy': 'الأمان والخصوصية',
    'uiHelpCenter': 'مركز المساعدة',
    'uiContentNeeded': 'المحتوى مطلوب',
    'uiDocumentUnavailable': 'المستند غير متاح',
    'uiMyCv': 'سيرتي الذاتية',
    'uiUploadedCv': 'السيرة المرفوعة',
    'uiCvSaved': 'تم حفظ السيرة الذاتية',
    'uiSaveUnavailable': 'الحفظ غير متاح',
    'uiDegree': 'الشهادة',
    'uiInstitution': 'المؤسسة',
    'uiYear': 'السنة',
    'uiPosition': 'المنصب',
    'uiProfessionalSummary': 'الملخص المهني',
    'uiEducation': 'التعليم',
    'uiExportComplete': 'اكتمل التصدير',
    'uiExportUnavailable': 'التصدير غير متاح',
    'uiCvPreview': 'معاينة السيرة الذاتية',
    'uiChooseTemplate': 'اختر قالباً',
    'uiSavedItems': 'العناصر المحفوظة',
    'uiAppliedOpportunities': 'الطلبات المقدمة',
    'uiCompanyProfile': 'ملف الشركة',
    'uiRefreshApplications': 'تحديث الطلبات',
    'uiRefreshSavedItems': 'تحديث العناصر',
    'uiOpps': 'فرص',
    'uiClearSearch': 'مسح البحث',
    'uiTrainingMenu': 'قائمة التدريب',
    'uiSavedResources': 'الموارد المحفوظة',
    'uiTrainingSubtitle': 'دورات وكتب وشهادات تصقل مسيرتك.',
    'uiEditingMessage': 'تعديل الرسالة',
    'uiDeleteForEveryone': 'حذف للجميع',
    'uiMuted': 'صامت',
    'uiArchived': 'مؤرشف',
    'uiAttach': 'إرفاق',
    'uiMyIdeas': 'أفكاري',
    'uiAttachmentUnavailable': 'المرفق غير متاح',
    'uiChatUnavailable': 'الدردشة غير متاحة',
    'uiScholarshipUnavailable': 'المنحة غير متاحة',
    'uiOpportunityUnavailable': 'الفرصة غير متاحة',
    'uiApplicationBlocked': 'الطلب محظور',
    'uiCvRequired': 'السيرة الذاتية مطلوبة',
    'uiAllSponsoredPrograms': 'جميع البرامج المدعومة',
    'uiPaidOnly': 'مدفوع فقط',
    'uiOpenLink': 'فتح الرابط',
    'uiContact': 'التواصل',
    'uiExternalLink': 'رابط خارجي',
    'uiAttachments': 'المرفقات',
    'uiBenefits': 'المزايا',
    'uiApplicationProcess': 'عملية التقديم',
    'uiSkillsNeeded': 'المهارات المطلوبة',
    'uiAdditionalInformation': 'معلومات إضافية',
    'uiExternalApplication': 'تقديم خارجي',
    'uiLink': 'الرابط',
    'uiExperienceLevel': 'مستوى الخبرة',
    'uiStartDate': 'تاريخ البدء',
    'uiLocation': 'الموقع',
    'uiType': 'النوع',
}

import json
from pathlib import Path

def add_extras():
    for locale, extras in [('en', EXTRA_EN), ('fr', EXTRA_FR), ('ar', EXTRA_AR)]:
        path = Path(f'lib/l10n/app_{locale}.arb')
        data = json.loads(path.read_text(encoding='utf-8'))
        added = 0
        for k, v in extras.items():
            if k not in data:
                data[k] = v
                if locale == 'en':
                    data[f'@{k}'] = {'description': k}
                added += 1
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf-8')
        print(f'[{locale}] extra keys added: {added}')

add_extras()

def fix_file(rel_path, spec):
    path = Path(rel_path)
    if not path.exists():
        print(f'  SKIP (not found): {rel_path}')
        return
    text = path.read_text(encoding='utf-8')
    original = text
    imp = spec['import']
    if imp not in text:
        after = spec['after']
        if after in text:
            text = text.replace(after, after + '\n' + imp, 1)
        else:
            print(f'  WARN anchor missing: {rel_path}')
    applied = 0
    for old, new in spec['replacements']:
        if old in text:
            text = text.replace(old, new)
            applied += 1
        else:
            print(f'  MISS [{path.name}]: {old[:60]}')
    if text != original:
        path.write_text(text, encoding='utf-8')
        print(f'  {path.name}: {applied}/{len(spec["replacements"])} fixes')
    else:
        print(f'  {path.name}: unchanged')

print('\n--- Dart replacements ---')
for rel_path, spec in FIXES.items():
    fix_file(rel_path, spec)
print('\nDone.')
