// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcQlwKznxxnom_W5nIhC4uT1HyxSAOqHk',
    appId: '1:620923930909:web:5583407a1c39bdcae9f9f4',
    messagingSenderId: '620923930909',
    projectId: 'avenirdz-7305d',
    authDomain: 'avenirdz-7305d.firebaseapp.com',
    storageBucket: 'avenirdz-7305d.firebasestorage.app',
    measurementId: 'G-82DGL6RKGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfBGGkSbr2Wd1hkYbZEOe4SzGHxJG4NbE',
    appId: '1:620923930909:android:f7c813939eb36050e9f9f4',
    messagingSenderId: '620923930909',
    projectId: 'avenirdz-7305d',
    storageBucket: 'avenirdz-7305d.firebasestorage.app',
  );
}
